apiVersion: v1
kind: Service
metadata:
  name: hands-on-app-service
spec:
  # hands-on-appというラベルがついているPodにトラウィックを分散
  selector:
    app: hands-on-app
  # ポート8081 の通信をPodの80ポートにリダイレクト
  ports:
  - port: 8082
    targetPort: 80
