apiVersion: v1
kind: Service
metadata:
  name: hands-on-app-service
spec:
  # 外部からもアクセスできるようにする
  type: LoadBalancer
  # hands-on-appというラベルがついているPodにトラウィックを分散
  selector:
    app: hands-on-app
  # ポート8081 の通信をPodの80ポートにリダイレクト
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
